### ISSUE TITLE
Respect recommended extension naming rules

### ISSUE THREAD

**Issue by josefglatz** [vkemeter/CustomFluidStyledContent#1]
- Allowed characters are: a-z (lowercase), 0-9 and '_' (underscore)
- The key must not being with one of the following prefixes: tx,user_,pages,tt_,sys_,ts_language_,csh_
- Extension keys cannot start or end with 0-9 and '_' (underscore)
- An extension key must have minimum 3, maximum 30 characters (not counting underscores)
- Do not use an '_' (underscore) before a number (0-9), e.g. myextension_2015

**Comment by vkemeter** [comment]
done. thx.
